-- liquibase formatted sql

-- changeset ТестоКРАБ:1694278717809-1
-- preconditions onFail:MARK_RAN onError:MARK_RAN
-- precondition-sql-check expectedResult:0 select count(*) from information_schema.tables where table_name = 'anime';
CREATE TABLE "anime" ("mal_id" INTEGER NOT NULL, "url" VARCHAR(255), "title" VARCHAR(255), "title_english" VARCHAR(255), "title_japanese" VARCHAR(255), "type" VARCHAR(50), "episodes" INTEGER, "airing" BOOLEAN, "status" VARCHAR(50), "duration" VARCHAR(50), "year" INTEGER, CONSTRAINT "anime_pkey" PRIMARY KEY ("mal_id"));

-- changeset ТестоКРАБ:1694278717809-2
-- preconditions onFail:MARK_RAN onError:MARK_RAN
-- precondition-sql-check expectedResult:0 select count(*) from information_schema.tables where table_name = 'anime_genre';
CREATE TABLE "anime_genre" ("anime_id" INTEGER, "genre_id" INTEGER);

-- changeset ТестоКРАБ:1694278717809-3
-- preconditions onFail:MARK_RAN onError:MARK_RAN
-- precondition-sql-check expectedResult:0 select count(*) from information_schema.tables where table_name = 'anime_image';
CREATE TABLE "anime_image" ("image_id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, "anime_id" INTEGER, "image_type" VARCHAR(50), "image_url" VARCHAR(255), "image_small_url" VARCHAR, "image_large_url" VARCHAR, CONSTRAINT "anime_images_pkey" PRIMARY KEY ("image_id"));

-- changeset ТестоКРАБ:1694278717809-4
-- preconditions onFail:MARK_RAN onError:MARK_RAN
-- precondition-sql-check expectedResult:0 select count(*) from information_schema.tables where table_name = 'anime_studio';
CREATE TABLE "anime_studio" ("anime_id" INTEGER, "studio_id" INTEGER);

-- changeset ТестоКРАБ:1694278717809-5
-- preconditions onFail:MARK_RAN onError:MARK_RAN
-- precondition-sql-check expectedResult:0 select count(*) from information_schema.tables where table_name = 'anime_title_synonym';
CREATE TABLE "anime_title_synonym" ("synonym_id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, "anime_id" INTEGER, "synonym" VARCHAR(255), CONSTRAINT "anime_title_synonyms_pkey" PRIMARY KEY ("synonym_id"));

-- changeset ТестоКРАБ:1694278717809-6
-- preconditions onFail:MARK_RAN onError:MARK_RAN
-- precondition-sql-check expectedResult:0 select count(*) from information_schema.tables where table_name = 'genre';
CREATE TABLE "genre" ("mal_id" INTEGER NOT NULL, "type" VARCHAR(50), "name" VARCHAR(200), "url" VARCHAR, CONSTRAINT "genre_pkey" PRIMARY KEY ("mal_id"));

-- changeset ТестоКРАБ:1694278717809-7
-- preconditions onFail:MARK_RAN onError:MARK_RAN
-- precondition-sql-check expectedResult:0 select count(*) from information_schema.tables where table_name = 'studio';
CREATE TABLE "studio" ("mal_id" INTEGER NOT NULL, "type" VARCHAR(50), "name" VARCHAR(200), "url" VARCHAR, CONSTRAINT "studio_pkey" PRIMARY KEY ("mal_id"));

-- changeset ТестоКРАБ:1694278717809-8
-- preconditions onFail:MARK_RAN onError:MARK_RAN
-- precondition-sql-check expectedResult:0 SELECT anime_id FROM information_schema.columns WHERE table_name='anime_genre' and column_name='anime_id';
ALTER TABLE "anime_genre" ADD CONSTRAINT "anime_genre_anime_id_fkey" FOREIGN KEY ("anime_id") REFERENCES "anime" ("mal_id") ON UPDATE NO ACTION ON DELETE CASCADE;

-- changeset ТестоКРАБ:1694278717809-9
-- preconditions onFail:MARK_RAN onError:MARK_RAN
-- precondition-sql-check expectedResult:0 SELECT genre_id FROM information_schema.columns WHERE table_name='anime_genre' and column_name='genre_id';
ALTER TABLE "anime_genre" ADD CONSTRAINT "anime_genre_genre_id_fkey" FOREIGN KEY ("genre_id") REFERENCES "genre" ("mal_id") ON UPDATE NO ACTION ON DELETE CASCADE;

-- changeset ТестоКРАБ:1694278717809-10

-- preconditions onFail:MARK_RAN onError:MARK_RAN
-- precondition-sql-check expectedResult:0 SELECT anime_id FROM information_schema.columns WHERE table_name='anime_image' and column_name='anime_id';
ALTER TABLE "anime_image" ADD CONSTRAINT "anime_images_anime_id_fkey" FOREIGN KEY ("anime_id") REFERENCES "anime" ("mal_id") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset ТестоКРАБ:1694278717809-11
-- preconditions onFail:MARK_RAN onError:MARK_RAN
-- precondition-sql-check expectedResult:0 SELECT anime_id FROM information_schema.columns WHERE table_name='anime_studio' and column_name='anime_id';
ALTER TABLE "anime_studio" ADD CONSTRAINT "anime_studio_anime_id_fkey" FOREIGN KEY ("anime_id") REFERENCES "anime" ("mal_id") ON UPDATE NO ACTION ON DELETE CASCADE;

-- changeset ТестоКРАБ:1694278717809-12
-- preconditions onFail:MARK_RAN onError:MARK_RAN
-- precondition-sql-check expectedResult:0 SELECT studio_id FROM information_schema.columns WHERE table_name='anime_studio' and column_name='studio_id';
ALTER TABLE "anime_studio" ADD CONSTRAINT "anime_studio_studio_id_fkey" FOREIGN KEY ("studio_id") REFERENCES "studio" ("mal_id") ON UPDATE NO ACTION ON DELETE CASCADE;

-- changeset ТестоКРАБ:1694278717809-13
-- preconditions onFail:MARK_RAN onError:MARK_RAN
-- precondition-sql-check expectedResult:0 SELECT anime_id FROM information_schema.columns WHERE table_name='anime_title_synonym' and column_name='anime_id';
ALTER TABLE "anime_title_synonym" ADD CONSTRAINT "anime_title_synonyms_anime_id_fkey" FOREIGN KEY ("anime_id") REFERENCES "anime" ("mal_id") ON UPDATE NO ACTION ON DELETE NO ACTION;

